# Generated by Django 5.2.7 on 2026-01-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='end_breakdown',
            field=models.CharField(choices=[('full', 'Full Day'), ('half', 'Half Day')], default='full', max_length=10),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='start_breakdown',
            field=models.CharField(choices=[('full', 'Full Day'), ('half', 'Half Day')], default='full', max_length=10),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='total_days',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('leave', 'Leave'), ('wfh', 'Work From Home')], max_length=20),
        ),
    ]
