# Generated by Django 5.2.7 on 2026-01-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_alter_repairingform_case_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PincodeData',
            fields=[
                ('pincode', models.CharField(db_index=True, max_length=6, primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('global_cargo_region', models.CharField(blank=True, max_length=10, null=True)),
                ('is_oda', models.BooleanField(blank=True, null=True)),
                ('deliverable', models.BooleanField(default=True)),
                ('safexpress_is_oda', models.BooleanField(blank=True, null=True)),
                ('bluedart_region', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Pincode Data',
                'verbose_name_plural': 'Pincode Data',
                'db_table': 'freight_pincode_data',
                'indexes': [models.Index(fields=['state'], name='freight_pin_state_db011e_idx'), models.Index(fields=['city'], name='freight_pin_city_2fcb7e_idx')],
            },
        ),
    ]
