# Generated by Django 5.2.7 on 2026-01-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_pincodedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcba_sn_old', models.CharField(blank=True, max_length=100, null=True, verbose_name='PCBA SN (old)')),
                ('pcba_sn_new', models.CharField(db_index=True, max_length=100, verbose_name='PCBA SN (new)')),
                ('component_type', models.CharField(blank=True, max_length=255, null=True)),
                ('specification', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remark', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(db_index=True, default=2025, help_text='Year of stock entry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock Item',
                'verbose_name_plural': 'Stock Items',
                'db_table': 'stock_items',
                'ordering': ['-year', 'component_type', 'pcba_sn_new'],
                'indexes': [models.Index(fields=['year', 'component_type'], name='stock_items_year_5b012b_idx'), models.Index(fields=['pcba_sn_new'], name='stock_items_pcba_sn_51b4f4_idx')],
            },
        ),
    ]
