# Generated by Django 5.2.7 on 2026-01-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_stockitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=100)),
                ('component_type', models.CharField(choices=[('Connector', 'Connector'), ('Main Board', 'Main Board'), ('Control Board', 'Control Board'), ('Cable', 'Cable'), ('Fuse', 'Fuse'), ('Relay', 'Relay'), ('Capacitor', 'Capacitor'), ('Transformer', 'Transformer'), ('Other', 'Other')], max_length=100)),
                ('description', models.TextField()),
                ('manager_name', models.CharField(max_length=200)),
                ('quantity_required', models.IntegerField()),
                ('required_to', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock Requisition',
                'verbose_name_plural': 'Stock Requisitions',
                'db_table': 'stock_requisitions',
                'ordering': ['-created_at'],
            },
        ),
    ]
