# Generated by Django 5.2.7 on 2026-01-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_stockrequisition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrequisition',
            name='component_type',
            field=models.CharField(max_length=100),
        ),
    ]
