# Generated by Django 5.2.7 on 2026-01-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_stockrequisition_approval_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequisition',
            name='approved_quantity',
            field=models.IntegerField(blank=True, help_text='Quantity approved to send by stock manager', null=True),
        ),
    ]
