# Generated by Django 5.2.7 on 2026-01-14 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0015_stockrequisition_approved_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=100)),
                ('component_type', models.CharField(max_length=100)),
                ('quantity_dispatched', models.IntegerField()),
                ('engineer_name', models.CharField(max_length=200)),
                ('dispatch_location', models.CharField(max_length=100)),
                ('dispatch_date', models.DateField()),
                ('courier_name', models.CharField(max_length=100)),
                ('tracking_number', models.CharField(max_length=100)),
                ('dispatch_remarks', models.TextField(blank=True, null=True)),
                ('dispatched_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='forms.stockrequisition')),
            ],
            options={
                'verbose_name': 'Dispatched Stock',
                'verbose_name_plural': 'Dispatched Stock',
                'db_table': 'dispatched_stock',
                'ordering': ['-dispatch_date', '-created_at'],
            },
        ),
    ]
