# Generated by Django 5.2.7 on 2026-01-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_dispatchedstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrequisition',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('dispatched', 'Dispatched')], default='pending', max_length=20),
        ),
    ]
