# Generated by Django 5.2.7 on 2026-01-21 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0020_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
