# Generated by Django 5.2.7 on 2026-01-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0021_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwardform',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
