# Generated by Django 5.2.7 on 2026-01-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0022_alter_inwardform_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwardform',
            name='accessories',
            field=models.JSONField(blank=True, default=list, help_text='Accessories selected (Data Logger, Stand)', null=True),
        ),
        migrations.AddField(
            model_name='outwardform',
            name='accessories',
            field=models.JSONField(blank=True, default=list, help_text='Accessories selected (Data Logger, Stand)', null=True),
        ),
        migrations.CreateModel(
            name='RequiredStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=100)),
                ('component_type', models.CharField(max_length=100)),
                ('quantity_required', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Required Stock',
                'verbose_name_plural': 'Required Stock',
                'db_table': 'required_stock',
                'unique_together': {('serial_number', 'component_type')},
            },
        ),
    ]
