# Generated by Django 5.2.7 on 2026-01-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0023_inwardform_accessories_outwardform_accessories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outwardform',
            name='control_card_changed',
            field=models.CharField(blank=True, help_text='Was control card changed? (Yes/No)', max_length=10),
        ),
        migrations.AddField(
            model_name='outwardform',
            name='new_serial_number',
            field=models.CharField(blank=True, help_text='New serial number if control card changed', max_length=100),
        ),
    ]
