# Generated by Django 5.2.7 on 2026-01-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0024_outwardform_control_card_changed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwardform',
            name='battery_id',
            field=models.CharField(blank=True, help_text='Unique Battery Serial Number', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outwardform',
            name='battery_id',
            field=models.CharField(blank=True, help_text='Unique Battery Serial Number', max_length=255, null=True),
        ),
    ]
