# Generated by Django 5.2.7 on 2026-01-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0025_inwardform_battery_id_outwardform_battery_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='outwardform',
            name='courier_name',
            field=models.CharField(blank=True, help_text='Courier name for delivery', max_length=100, null=True),
        ),
    ]
