# Generated by Django 5.2.7 on 2026-01-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0026_outwardform_courier_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwardform',
            name='pcb_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='No of Quantity', null=True),
        ),
        migrations.AddField(
            model_name='inwardform',
            name='pcb_serial_number',
            field=models.CharField(blank=True, help_text='PCB Serial Number', max_length=255, null=True),
        ),
    ]
