# Generated by Django 5.2.7 on 2026-01-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0028_repairingform_pcb_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwardform',
            name='inward_object',
            field=models.CharField(blank=True, help_text='Type of object for inward (Inverter, Battery, PCB)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='outwardform',
            name='outward_object',
            field=models.CharField(blank=True, help_text='Type of object for outward (Inverter, Battery, PCB)', max_length=50, null=True),
        ),
    ]
