# Generated by Django 5.2.7 on 2026-01-28 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0030_inwardform_user_outwardform_user_repairingform_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchedstock',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who filled the form', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicereportform',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who filled the form', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockrequisition',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who filled the form', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
