# Generated by Django 5.2.7 on 2026-01-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0031_dispatchedstock_user_servicereportform_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockitem',
            options={'ordering': ['-shipment_date', '-year', 'component_type', 'pcba_sn_new'], 'verbose_name': 'Stock Item', 'verbose_name_plural': 'Stock Items'},
        ),
        migrations.AddField(
            model_name='stockitem',
            name='shipment_date',
            field=models.DateField(blank=True, help_text='Date of shipment received', null=True),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['shipment_date'], name='stock_items_shipmen_b62547_idx'),
        ),
    ]
