# Generated by Django 5.2.7 on 2026-02-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0032_alter_stockitem_options_stockitem_shipment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='pcba_sn_new',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='PCBA SN (new)'),
        ),
    ]
