# Generated by Django 5.2.7 on 2026-02-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0034_load_stock_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='pincodedata',
            name='bigship_is_oda',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
