# Generated by Django 5.2.7 on 2026-02-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0035_pincodedata_bigship_is_oda'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Employee ID/Number', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is employee currently active'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='joining_date',
            field=models.DateField(blank=True, help_text='Date of Joining', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='region',
            field=models.CharField(blank=True, help_text='Region/Territory', max_length=100),
        ),
    ]
