# Generated by Django 5.2.7 on 2026-02-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0036_userprofile_employee_id_userprofile_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Profile Photo', null=True, upload_to='profile_photos/'),
        ),
    ]
