# Generated by Django 5.2.7 on 2026-02-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0037_userprofile_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('National', 'National Holiday'), ('Festival', 'Festival'), ('Regional', 'Regional Holiday'), ('Optional', 'Optional Holiday')], max_length=50)),
                ('is_floating', models.BooleanField(default=False, help_text='True if employees can choose this as floating holiday (max 3)')),
                ('description', models.TextField(blank=True, help_text='Additional description or region-specific info')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'db_table': 'holidays',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date'], name='holidays_date_c1d23c_idx'), models.Index(fields=['is_floating'], name='holidays_is_floa_99856f_idx')],
            },
        ),
    ]
