# Generated by Django 5.2.7 on 2026-02-17 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0038_holiday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, help_text='Date of check-in')),
                ('check_in_time', models.DateTimeField(help_text='Exact timestamp when employee checked in')),
                ('check_in_latitude', models.DecimalField(decimal_places=6, help_text='GPS latitude at check-in', max_digits=9)),
                ('check_in_longitude', models.DecimalField(decimal_places=6, help_text='GPS longitude at check-in', max_digits=9)),
                ('check_in_location', models.CharField(help_text='Address/location name at check-in', max_length=255)),
                ('check_out_time', models.DateTimeField(blank=True, help_text='Exact timestamp when employee checked out', null=True)),
                ('check_out_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude at check-out', max_digits=9, null=True)),
                ('check_out_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude at check-out', max_digits=9, null=True)),
                ('check_out_location', models.CharField(blank=True, help_text='Address/location name at check-out', max_length=255)),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Total hours worked (automatically calculated)', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Employee who checked in', on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Check-In/Check-Out',
                'verbose_name_plural': 'Check-Ins/Check-Outs',
                'db_table': 'employee_checkin',
                'ordering': ['-date', '-check_in_time'],
                'indexes': [models.Index(fields=['user', 'date'], name='employee_ch_user_id_e6c44b_idx'), models.Index(fields=['date'], name='employee_ch_date_c99343_idx')],
            },
        ),
    ]
