# Generated by Django 5.2.7 on 2026-02-17 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0039_checkinout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ping_time', models.DateTimeField(auto_now_add=True, help_text='When location was captured')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS Latitude', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS Longitude', max_digits=9, null=True)),
                ('location_address', models.TextField(blank=True, help_text='Reverse geocoded address')),
                ('ping_type', models.CharField(choices=[('checkin', 'Check-In'), ('hourly', 'Hourly Ping'), ('checkout', 'Check-Out'), ('recovery', 'Coverage Recovery')], default='hourly', max_length=20)),
                ('is_location_available', models.BooleanField(default=True, help_text='Was location available at ping time?')),
                ('coverage_gap_seconds', models.IntegerField(default=0, help_text='Seconds without location before this ping')),
                ('accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True)),
                ('device_info', models.CharField(blank=True, help_text='Browser/Device details', max_length=200)),
                ('checkin', models.ForeignKey(blank=True, help_text='Associated check-in session', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='forms.checkinout')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Location Tracking',
                'verbose_name_plural': 'Location Tracking Records',
                'db_table': 'employee_location_tracking',
                'ordering': ['-ping_time'],
                'indexes': [models.Index(fields=['user', 'ping_time'], name='employee_lo_user_id_da00a4_idx'), models.Index(fields=['checkin', 'ping_time'], name='employee_lo_checkin_46ea80_idx'), models.Index(fields=['ping_time'], name='employee_lo_ping_ti_3f6995_idx')],
            },
        ),
    ]
