# Generated by Django 5.2.7 on 2026-02-17 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0040_locationtracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTravelSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of travel')),
                ('total_distance_km', models.DecimalField(decimal_places=2, default=0, help_text='Total distance travelled in kilometers', max_digits=10)),
                ('location_count', models.IntegerField(default=0, help_text='Number of location pings recorded')),
                ('first_ping_time', models.DateTimeField(blank=True, help_text='Check-in time', null=True)),
                ('last_ping_time', models.DateTimeField(blank=True, help_text='Check-out time', null=True)),
                ('work_duration_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Total work hours', max_digits=5, null=True)),
                ('start_location', models.TextField(blank=True, help_text='Check-in location address')),
                ('end_location', models.TextField(blank=True, help_text='Check-out location address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_summary', to='forms.checkinout')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_travel_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Travel Summary',
                'verbose_name_plural': 'Daily Travel Summaries',
                'db_table': 'daily_travel_summary',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='daily_trave_user_id_7364ea_idx'), models.Index(fields=['date'], name='daily_trave_date_d65069_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
