# Generated by Django 5.2.7 on 2026-02-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0046_inwardform_inward_id_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='outwardform',
            name='pcb_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='No of Quantity', null=True),
        ),
        migrations.AddField(
            model_name='outwardform',
            name='pcb_rating',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='outwardform',
            name='pcb_serial_number',
            field=models.CharField(blank=True, help_text='PCB Serial Number', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outwardform',
            name='pcb_specification',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
